package com.pos.enums;

public enum ResponseEnum {
    SUCCESS,
    ERROR,
    ACCOUNT_ALREADY_EXIST, SIGN_IN_FAILED,
    ACCOUNT_NOT_FOUND, CLIENT_ALREADY_EXIST, CLIENT_NOT_FOUND, PIC_NOT_FOUND, ACCESS_DENIED
}
